# Generated by Django 5.0.7 on 2026-09-14 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['is_notes_collection', 'module_number']},
        ),
        migrations.AddField(
            model_name='module',
            name='is_notes_collection',
            field=models.BooleanField(default=False, help_text='If true, this folder is shown as Notes/PDFs rather than a numbered module.'),
        ),
    ]
